### ISSUE TITLE
Test cases for all operations

### ISSUE THREAD

**Issue by nimit-kodrani** [nimit-kodrani/basic-calculator#9]
Test cases for all operations

**Comment by DivyeshAgarwaliitg21** [comment]
I can add tests for multiply
please assign me

**Comment by nimit-kodrani** [comment]
@DivyeshAgarwaliitg21 assigning it to you!
please add test cases for other operations also, and not just multiply

**Comment by DivyeshAgarwaliitg21** [comment]
ok sure.
